# Generated by Django 4.1.2 on 2023-03-27 20:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedetails',
            name='description_one',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homedetails',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homedetails',
            name='title_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
